const GET_ALL_LOANS = 'GET_ALL_LOANS';
const GET_SINGLE_LOAN = 'GET_SINGLE_LOAN';
const GET_LOAN_REPAYMENTS = 'GET_LOAN_REPAYMENTS';
const GET_LOANS_SUCESS = 'GET_LOANS_SUCESS';
const GET_LOANS_FAILURE = 'GET_LOANS_FAILURE';
const POST_LOAN_REPAYMENT = 'POST_LOAN_REPAYMENT';
const VERIFY_LOAN_REQEST = 'VERIFY_LOAN_REQEST';
const APPLY_FOR_LOAN = 'APPLY_FOR_LOAN';

export {
  GET_ALL_LOANS, GET_LOANS_SUCESS,
  GET_LOANS_FAILURE, GET_SINGLE_LOAN, VERIFY_LOAN_REQEST,
  POST_LOAN_REPAYMENT, GET_LOAN_REPAYMENTS, APPLY_FOR_LOAN
};
