const GET_ALL_CLIENTS = 'GET_ALL_CLIENTS';
const GET_SINGLE_CLIENT = 'GET_SINGLE_CLIENT';
const UPDATE_SINGLE_CLIENT = 'UPDATE_SINGLE_CLIENT';
const GET_CLIENTS_SUCESS = 'GET_CLIENTS_SUCESS';
const GET_CLIENTS_FAILURE = 'GET_CLIENTS_FAILURE';

export {
  GET_ALL_CLIENTS, GET_CLIENTS_SUCESS, GET_CLIENTS_FAILURE, GET_SINGLE_CLIENT, UPDATE_SINGLE_CLIENT
};
