const SUCCESS_MESSAGE_ALERT = 'SUCCESS_MESSAGE_ALERT';
const FAILURE_MESSAGE_ALERT = 'FAILURE_MESSAGE_ALERT';
const CLEAR_MESSAGE_ALERT = 'CLEAR_MESSAGE_ALERT';

export {
  SUCCESS_MESSAGE_ALERT, FAILURE_MESSAGE_ALERT, CLEAR_MESSAGE_ALERT
};
