export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_AUTH_SUCESS = 'USER_AUTH_SUCESS';
export const USER_AUTH_FAILURE = 'USER_AUTH_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT_SUCESS';
