const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
const USER_AUTH_SUCESS = 'USER_AUTH_SUCESS';
const USER_AUTH_FAILURE = 'USER_AUTH_FAILURE';


export {
  USER_LOGIN_REQUEST, USER_SIGNUP_REQUEST, USER_AUTH_SUCESS, USER_AUTH_FAILURE
};
